### PR TITLE
Migrate to Swift 2 and Add support for ADB over Bluetooth

### PR DESCRIPTION
**Pull request by Dibel**

### CODE REVIEW

**Comment by mortenjust** [comment]
This looks awesome, thanks for taking the time. It looks good to me. Have you had a chance to test this over the last week?

**Comment by Dibel** [comment]
Yes, I've tested the Android part. I don't have an iOS device so we need more tests on iOS devices.

**Comment by MadMacMad** [comment]
Hey so great this tool.... well if i find some time i will check it on iOS ...
manx thx
M.

**Comment by mortenjust** [comment]
Merged and released! - thanks again, and please help test 1.3

**Pull request merged**
